"""The only contract between Rocky and the operating system. macos.py and windows.py implement it;
nothing outside rocky/platform/ may call the OS directly."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from ..models import Snapshot


class Platform(Protocol):
    name: str  # "macos" | "windows"

    # --- apps and navigation (fast path) ---
    def installed_apps(self) -> list[str]: ...
    def frontmost_app(self) -> str: ...
    def open_app(self, name: str) -> None: ...
    def focus_app(self, name: str, timeout: float = 2.0) -> bool: ...
    def open_url(self, url: str) -> None: ...

    # --- input ---
    def type_text(self, text: str) -> None: ...
    def press(self, key: str, modifiers: list[str] | None = None, times: int = 1) -> None: ...
    def scroll(self, direction: str, amount: int = 3) -> None: ...
    def click(self, x: float, y: float, button: str = "left", clicks: int = 1) -> None: ...

    # --- system ---
    def volume(self, op: str) -> str: ...  # up | down | mute | unmute -> spoken result
    def media(self, op: str) -> None: ...  # play_pause | next | previous
    def system(self, op: str) -> str: ...  # dark_mode | lock | sleep_display | screenshot

    # --- perception (goal path) ---
    def snapshot(self, max_items: int = 120) -> Snapshot: ...
    def focused_role(self) -> str: ...  # role of the focused UI element, e.g. "AXSecureTextField", "" if none
    def screenshot(self, path: Path | None = None) -> Path: ...

    # --- shortcuts vocabulary the router may offer, e.g. {"copy": ("c", ["cmd"])} ---
    def shortcuts(self) -> dict[str, tuple[str, list[str]]]: ...

    # --- permissions ---
    def check_permissions(self) -> dict[str, bool]: ...
